ALTER TABLE GaiaCatalog 
ADD COLUMN mag DOUBLE PRECISION NOT NULL;

-- ALTER TABLE GaiaCatalog 
-- ALTER COLUMN id DROP IDENTITY IF EXISTS;


-- ALTER TABLE GaiaCatalog 
-- ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- ADD GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY { ( sequence_option ) }